CREATE TABLE CONSISTS_OF
(
ROUTE_NO INT,
TRAIN_ID INT,
SCHEDULE_ID INT,
STATION_ID INT,
STOP_NO INT,
ARRIVAL_TIMEVARCHAR(20),
DEPARTURE_TIMEVARCHAR(20),
PRIMARY KEY(ROUTE_NO,TRAIN_ID,SCHEDULE_ID,STATION_ID),
FOREIGN KEY(ROUTE_NO) REFERENCES ROUTE(ROUTE_NO),
FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN(TID),
FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULES(SCHEDULE_ID),
FOREIGN KEY(STATION_ID) REFERENCES STATION(S_ID)
);

INSERT INTO CONSISTS_OF(ROUTE_NO INT,
TRAIN_ID,
SCHEDULE_ID,
STATION_ID,
STOP_NO,
ARRIVAL_TIME,
DEPARTURE_TIME)
VLAUES(13,2,1,2,3,”12PM”,”9AM”);

INSERT INTO CONSISTS_OF(ROUTE_NO INT,
TRAIN_ID,
SCHEDULE_ID,
STATION_ID,
STOP_NO,
ARRIVAL_TIME,
DEPARTURE_TIME)
VLAUES(25,4,2,4,1,”1AM”,”6PM”);

INSERT INTO CONSISTS_OF(ROUTE_NO INT,
TRAIN_ID,
SCHEDULE_ID,
STATION_ID,
STOP_NO,
ARRIVAL_TIME,
DEPARTURE_TIME)
VLAUES(92,13,5,1,3,”9AM”,”5PM”);

INSERT INTO CONSISTS_OF(ROUTE_NO INT,
TRAIN_ID,
SCHEDULE_ID,
STATION_ID,
STOP_NO,
ARRIVAL_TIME,
DEPARTURE_TIME)
VLAUES(8,3,2,4,2,”6PM”,”1AM”);

INSERT INTO CONSISTS_OF(ROUTE_NO INT,
TRAIN_ID,
SCHEDULE_ID,
STATION_ID,
STOP_NO,
ARRIVAL_TIME,
DEPARTURE_TIME)
VLAUES(45,12,6,3,1,”1PM”,”9AM”);