CREATE TABLE ROUTE
(
ROUTE_NO INT,
TOTAL_STOPS INT,
SCHEDULE_ID INT,
TRAIN_ID INT,
PRIMARY KEY(ROUTE_NO,SCHEDULE_ID,TRAIN_ID),
FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULES(SCHEDULE_ID),
FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN(TID)
);

INSERT INTO ROUTE( ROUTE_NO,
TOTAL_STOPS,
SCHEDULE_ID,
TRAIN_ID) VALUES(13,2,1,2);

INSERT INTO ROUTE( ROUTE_NO,
TOTAL_STOPS,
SCHEDULE_ID,
TRAIN_ID) VALUES(25,4,3,4);

INSERT INTO ROUTE( ROUTE_NO,
TOTAL_STOPS,
SCHEDULE_ID,
TRAIN_ID) VALUES(61,0,7,41);

INSERT INTO ROUTE( ROUTE_NO,
TOTAL_STOPS,
SCHEDULE_ID,
TRAIN_ID) VALUES(8,6,2,3);