CREATE TABLE SCHEDULES
(
SCHEDULES_ID INT,
SOURCE VARCHAR(20),
DESTINATION VARCHAR(20),
START_TIMEVARCHAR(20),
END_TIME VARCHAR(20),
TRAIN_ID INT,
ROUTE_NO INT,
PRIMARY KEY(SCHEDULES_ID,TRAIN_ID,ROUTE_NO),
FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN(TID),
FOREIGN KEY(ROUTE_NO) REFERENCES ROUTE(ROUTE_NO)
);

INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME,
END_TIME,
TRAIN_ID ,
ROUTE_NO ) VALUES(1,”BELGAM”, “GOA”,”12PM”,”1:30PM”,2,13);


INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME,
END_TIME,
TRAIN_ID ,
ROUTE_NO ) VALUES(2,”BANGLORE”, CHANDIGARH”,”1AM”,”12:30PM”,3,8);


INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME,
END_TIME,
TRAIN_ID ,
ROUTE_NO)  VALUES(3,”DELHI”, “CHANDIGARH”,”1AM”,”2:30AM”,4,25);


INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME),
END_TIME,
TRAIN_ID ,
ROUTE_NO)  VALUES(4,”HUBBLI”, “BANGLORE”,”3PM”,”1AM”,5,19);


INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME),
END_TIME,
TRAIN_ID ,
ROUTE_NO)  VALUES(5,”BELGAVI”, “MUMBAI”,”9PM”,”6AM”,13,92);


INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME,
END_TIME,
TRAIN_ID ,
ROUTE_NO) VALUES(6,”PUNE”, “BELGAM”,”2PM”,”9PM”,12,45);


INSERT INTO SCHEDULES ( SCHEDULES_ID,
SOURCE,
DESTINATION,
START_TIME,
END_TIME,
TRAIN_ID ,
ROUTE_NO) VALUES(7,”PUNE”, “MUMBAI”,”12PM”,”2PM”,41,61);